### Grüne Wirtschaft

In einem wegweisenden Gebrauch des Begriffs „grüne Wirtschaft" lancierten David Pearce und Edward Barbier 1989 ihre bahnbrechende *Blueprint for a Green Economy*-Reihe. Die Reihe war die erste, die wirtschaftliche Rahmenkonzepte und programmatische Ansätze zur Erreichung der doppelten Ziele wirtschaftlicher Prosperität und ökologischen Wohlergehens vorstellte [z. B. @pearceBluePrintGreen1989; @pearceSustainableDevelopmentEconomics2000; @barbierNewBlueprintGreen2013]. Das Kernprinzip der Grünen Wirtschaft stellt die traditionelle Ansicht in Frage, dass Wirtschaftswachstum und ökologisches Wohlergehen grundsätzlich unvereinbar sind. Es schlägt einen Paradigmenwechsel vor, weg von Verboten und Einschränkungen. Stattdessen plädiert es für wirtschaftliche Anreize und Strategien, die die ökologische Nachhaltigkeit fördern und gleichzeitig positive Modelle wirtschaftlicher und technologischer Entwicklung begünstigen, die sowohl mit ökologischen als auch mit sozialen Zielen vereinbar sind.

Im Vorfeld von Rio+20, der UNO-Konferenz für Nachhaltige Entwicklung 2012, wurde das Konzept der Grünen Wirtschaft schliesslich zu einem Leitprinzip entwickelt, das die Debatte prägte [@unepGreenEconomyPathways2011; @barGreenEconomyDiscourses2011]. „Grüne Wirtschaft" war eines von zwei Kernthemen von Rio+20; das andere war der „institutionelle Rahmen" für Nachhaltige Entwicklung. Dementsprechend wurden 2011 und 2012 zahlreiche Dokumente zur Grünen Wirtschaft veröffentlicht, und eine wegweisende Definition des Begriffs wurde vom Organisationsgremium von Rio+20, dem Umweltprogramm der Vereinten Nationen (UNEP), im Bericht *Towards a Green Economy: Pathways to Sustainable Development and Poverty Eradication* [@unepGreenEconomyPathways2011] veröffentlicht. Auch die OECD leistete mit ihrer Entschliessung zu „Grünem Wachstum" [@oecdDeclarationGreenGrowth2009] einen eigenen Beitrag zur Reaktion auf die Finanzkrise.

::: callout-note
„Das UNEP definiert eine grüne Wirtschaft als eine solche, die zu verbessertem menschlichem Wohlbefinden und sozialer Gerechtigkeit führt und gleichzeitig Umweltrisiken und ökologische Knappheiten erheblich reduziert. Im einfachsten Sinne kann eine grüne Wirtschaft als eine solche verstanden werden, die CO~2~-arm, ressourceneffizient und sozial inklusiv ist. In einer grünen Wirtschaft sollten Einkommens- und Beschäftigungswachstum durch öffentliche und private Investitionen angetrieben werden, die Kohlenstoffemissionen und Umweltverschmutzung reduzieren, die Energie- und Ressourceneffizienz verbessern und den Verlust von Biodiversität und Ökosystemleistungen verhindern." [@unepGreenEconomyPathways2011, p. 2]
:::

Obwohl Rio+20 das Konzept der Grünen Wirtschaft zementierte, war die Notwendigkeit eines grundlegenden globalen Umdenkens bereits weitgehend akzeptiert. Es war deutlich geworden, dass Umweltschutzmassnahmen zwar Geld kosten, aber auch positive wirtschaftliche Auswirkungen haben, indem sie Arbeitsplätze schaffen [vgl. z. B. @umweltbundesamtubaBeschaftigungswirkungenUmweltschutzesFur2008] und Innovationen in technologischen Effizienzfortschritten anspornen [vgl. z. B. @vonweizsackerFaktorVierDoppelter1995]. Das Konzept der Grünen Wirtschaft systematisiert solche Erkenntnisse und fordert Programme, um die scheinbaren Widersprüche zwischen Wirtschaft und Ökologie, Wachstum und Ressourcenschonung sowie Wohlstand und Umweltschutz zu überwinden. Das Konzept markiert damit einen bedeutenden Paradigmenwechsel. Die Einhaltung planetarer Grenzen oder ökologischer Leitlinien in einer Grünen Wirtschaft bedeutet nicht zwangsläufig, auf Wirtschaftswachstum und technologischen Fortschritt zu verzichten [@rockstromSafeOperatingSpace2009; @sachverstandigenratfurumweltfragensruUmweltgutachten2012Verantwortung2012]. Stattdessen lautet die Idee, dass wir durch die Harmonisierung dieser scheinbar widersprüchlichen Ziele sie noch effizienter erreichen können. Der EU Green Deal exemplifiziert dieses Konzept. Die EU strebt an, bis 2050 der erste klimaneutrale Kontinent zu werden, mit dem Ziel einer modernen, ressourceneffizienten und wettbewerbsfähigen Wirtschaft mit netto null Treibhausgasemissionen. Dieser Plan soll Wachstum vom Ressourcenverbrauch entkoppeln und gleichzeitig einen gerechten Übergang gewährleisten, der niemanden zurücklässt.

### Fazit

Die Kernthese der Grünen Wirtschaft lautet, dass ökologische und wirtschaftliche Ziele kein Widerspruch sind. Stattdessen können sie durch geeignete wirtschaftliche Anreize und Strategien miteinander vereinbart werden. Die Grüne Wirtschaft zielt darauf ab, sowohl Wirtschaftswachstum als auch ökologische Nachhaltigkeit durch öffentliche und private Investitionen in emissionsarme, ressourceneffiziente und sozial gerechte Wirtschaftssysteme zu fördern.

Kritiker*innen haben jedoch Bedenken hinsichtlich der Wirksamkeit von Massnahmen der Grünen Wirtschaft geäussert. Sie argumentieren, dass die vorgeschlagenen Technologien und Anreize nicht ausreichen, um die notwendigen weitreichenden systemischen Veränderungen herbeizuführen. Eine übermässige Betonung von Wirtschaftswachstum und technologischen Lösungen könnte wesentliche strukturelle und verhaltensbezogene Veränderungen vernachlässigen. Und sie warnen, dass der globale Übergang zu einer Grünen Wirtschaft benachteiligte Gemeinschaften und Entwicklungsländer zurücklassen könnte, wenn deren spezifische Bedürfnisse nicht berücksichtigt werden.
