project:
  type: book
  output-dir: docs
  resources:
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"

execute:
  engine: knitr
  echo: false

book:
  title: "Nachhaltigkeit: Grundlagen und Herausforderungen"
  subtitle: "Skript zur Grundlagenvorlesung M1_1 im Bachelor Studienprogramm Nachhaltige Entwicklung"
  favicon: images/
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://cdeteaching.github.io/NEgrundlagen/
  
  sidebar:
    search: true
    logo: images/cdelogo_e.png
    tools:
      - icon: file-earmark-pdf
        href: https://cdeteaching.github.io/NEgrundlagen/pdf/NEgrundlagen.pdf
        text: "Skript (PDF)"
    
  page-footer:
    border: true
    left: |
      "Ein Angebot von <a href="www.cde.unibe.ch/">![](/images/cdelogo_e.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |

    right: |
      Dieses Buch wurde mit <a href="https://quarto.org/">Quarto</a> erstellt. Dieses Werk ist lizenziert unter einer [CC-BY-NC-ND 4.0 Int Lizenz](https://creativecommons.org/licenses/by-nc-nd/4.0/)

  

  chapters:
  - index.qmd
  - intro.qmd
  - part: "Die Herausforderungen des 21. Jahrhunderts für Nachhaltigkeit erfassen und verstehen lernen"
    chapters:
    - 1_understanding/1_intro.qmd
    - 2_approaches/2_intro.qmd
  - part: "Handlungsfelder der Nachhaltigkeit: Analyse und Strategien zur Transformation von (un-)nachhaltigen Systemen"
    chapters:
    - 3_ecological-sustainability/3_intro.qmd
    - 4_social-sustainability/4_intro.qmd
    - 5_economic-sustainability/5_intro.qmd

    
    
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme:
      - theme.css
      - theme.scss
    df-print: kable

  pdf:
  # render pdf to separate folder -> do it manually via terminal
  # "quarto render --to pdf --output SP_IDTD.pdf --output-dir pdf"
    documentclass: book
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    urlcolor: "blue"
    number-depth: 3
    papersize: a4
    fig-pos: "H"
    classoption: openany
    pdf-engine: xelatex
    metadata:
      title: "book"
    callout-icon: false
    keep-tex: true
    tables: true
    include-in-header:
      text: |
        \usepackage{booktabs}
        \usepackage{longtable}
        \usepackage{microtype}
        \hyphenpenalty=10000
        \exhyphenpenalty=10000
        \usepackage[skins]{tcolorbox}
        \makeatletter
        \pgfkeys{/tcb/breakable/.code=\relax}
        \makeatother

