project:
  type: book
  output-dir: docs
  resources:
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"

execute:
  engine: knitr
  echo: false

lang: de-CH

book:
  title: "Nachhaltigkeit: Grundlagen und Herausforderungen"
  subtitle: "Skript zur Grundlagenvorlesung M1_1 im Bachelor Studienprogramm Nachhaltige Entwicklung"
  cover-image: CoverLehrbuch.png
  favicon: images/
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://cdeteaching.github.io/NEgrundlagen/
  repo-actions: [issue]

  sidebar:
    search: true
    logo: images/cdelogo_e.png
    tools:
      - icon: file-earmark-pdf
        href: https://github.com/CDEteaching/NEgrundlagen/blob/main/pdf/Lehrbuch_M1_1.pdf
        text: "Skript (PDF)"
    
  page-footer:
    border: true
    left: |
      "Ein Angebot von <a href="www.cde.unibe.ch/">![](/images/cdelogo_e.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |

    right: |
      Dieses Buch wurde mit <a href="https://quarto.org/">Quarto</a> erstellt. Dieses Werk ist lizenziert unter einer [CC-BY-NC-SA 4.0 Int Lizenz](https://creativecommons.org/licenses/by-nc-sa/4.0/)

  

  chapters:
  - index.qmd
  - intro.qmd
  - part: "Die Herausforderungen des 21. Jahrhunderts für Nachhaltigkeit erfassen und verstehen lernen"
    chapters:
    - 1_understanding/1_intro.qmd
  - part: "Ansätze zur Nachhaltigen Entwicklung"
    chapters:
    - 2_approaches/2_intro.qmd
  - part: "Handlungsfelder der Nachhaltigkeit: Analyse und Strategien zur Transformation von (un-)nachhaltigen Systemen"
    chapters:
    - 3_ecological-sustainability/3_intro.qmd
    - 4_social-sustainability/4_intro.qmd
    - 5_economic-sustainability/5_intro.qmd
  - references.qmd

bibliography: references.bib

number-depth: 3

format:
  html:
    cover-image: cover.png
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme:
      light: [theme.scss]
      dark: [darkly]
    toggle: true
    callout-icon: false  
    css: webex.css
    include-after-body: webex.js
    df-print: kable

  pdf:
    output-file: Lehrbuch_M1_1
  # render pdf to separate folder -> do it manually via terminal
  # "quarto render --to pdf --output Lehrbuch_M1_1.pdf --output-dir pdf"
    documentclass: scrreprt
    classoption: ["oneside", "openany"]
    cover-image: CoverLehrbuch.png

    mainfont: "Alegreya"
    sansfont: "Source Sans Pro"
    urlcolor: "blue"

    number-depth: 3
    papersize: a4
    fig-pos: "H"
    pdf-engine: xelatex
    callout-icon: false

    keep-tex: true
    tables: true
    include-in-header:
      text: |
        \usepackage{booktabs}
        \usepackage{longtable}
        \usepackage{microtype}
        \usepackage{pdfpages}
        \usepackage[font=footnotesize,labelfont={footnotesize}]{caption}
        \renewcommand{\maketitle}{}
        \usepackage[skins,breakable]{tcolorbox}

    include-before-body:
      text: |
        \includepdf[pages=1]{CoverLehrbuch.pdf}

